#%RAML 1.0 Trait
 500:
        description: Internal server error
        body:
          application/json:
            example:
              {
                "message": "An unexpected error occurred"
              }
